### ISSUE TITLE
Support multiple active environments

### ISSUE THREAD

**Issue by bbenne10** [ssbb/pyenv-mode-auto#7]
Currently, pyenv-mode-auto assumes that any `.python-version` file will contain one line with one active version. However, pyenv allows for the cascade of environments (I presume via the shims looking through one and falling back to the next configured environment if a given command doesn't exist in the first environment, but I have not checked this). This cascading setup is relatively common for `tox`-oriented workflows, but currently breaks pyenv-mode-auto.

I'm not sure how such a simple library could emulate this behavior fully, but I have a small change that fixes it in all of my cases: simply activate the first listed environment.

This looks as follows: 

```emacs lisp
(defun pyenv-mode-auto-hook ()
  "Automatically activates pyenv version if .python-version file exists."
  (f-traverse-upwards
   (lambda (path)
     (let ((pyenv-version-path (f-expand ".python-version" path)))
       (if (f-exists? pyenv-version-path)
           (progn
             (pyenv-mode-set (car (s-lines (s-trim (f-read-text pyenv-version-path 'utf-8)))))
             t))))))
```

Note the addition of the use of `car` and `s-lines`. 

If you'd like, I'll happily work this into a PR. I wanted to open the floor for some discussion before I did that, however.

**Comment by bbenne10** [comment]
@ssbb: I just updated packages and was bitten by this bug again. Would you merge a PR for this functionality? Would you like further discussion on the matter? Or should I just close this?

**Comment by ssbb** [comment]
Hi @bbenne10 ! Thank you and sorry for the delay. Just pushed this fix to master and it should be updated on MELPA soon 👍

**Comment by bbenne10** [comment]
Holy hell that was fast! Thanks for the quick turnaround!
