### ISSUE TITLE
Question : Is this replacement for pyvenv-workon ?

### ISSUE THREAD

**Issue by mandarvaze** [ssbb/pyenv-mode-auto#9]
I was earlier using `pyvenv` and when I manually set `pyvenv-workon` to the same virtualenv, everything used to work, but there was always this **manual** step to select the virtualenv. So I came here looking for "automation"

I (think) I have installed `pyenv-mode-auto` correctly (It is really simple) yet, I am not sure it is working for me.
`.python-version` exists in the parent folder of the file I have opened.

To troubleshoot, I even manually `pyenv-mode-set` to the correct virtualenv - yet after doing that `M-! which python` reports `/usr/local/bin/python` **not** the one from  my virtualenv.

What am I doing wrong ? (or may be I am expecting something that is not supposed to work)

Also, what are the steps to troubleshoot ?

**Comment by ssbb** [comment]
Hi @mandarvaze! I think it's more pyenv-mode question. This package (pyenv-mode-auto) just a helper to automatically activate version based on `.python-version` file within project root (and intended to be used with pyenv-mode).

BTW as I know pyenv-mode does not change `exec-path` so it will report `/usr/local/bin/python`. pyenv-mode just set `PYENV_VERSION` env variable and `python-shell-virtualenv-path` custom variable.

You can check that correct version is used with something like `M-x run-python`
